# POST http://localhost:8000/v1/player/many
# Content-Type: application/json

# [
#     {
#         "long_name": "Sub Zero Project",
#         "value_eur": "75000"
#     },
#     {
#         "long_name": "ZZZZZ",
#         "value_eur": "15500000"
#     }
# ]

# GET http://localhost:1705/v1/player

POST http://localhost:1705/auth/register
Content-Type: application/json

{
    "username": "dannguyen",
    "password": "12345"
}