## ADD MANY
POST http://localhost:8000/v1/player/many
Content-Type: application/json

[
    {
        "long_name": "Nguyen Di Dan",
        "player_position": ["RW", "CAM"],
        "value_eur": "17000",
        "age": 21,
        "dob": "2002-05-17",
        "club_name": "HungYen City",
        "nationality_name": "Vietnam",
        "player_face_url": "https://cdn.sofifa.net/players/200/145/22_120.png" 
    },
    {
        "long_name": "Nguyen Van Thang",
        "player_position": ["LW", "ST"],
        "value_eur": "24800",
        "age": 19,
        "dob": "2004-04-28",
        "club_name": "AnThi District",
        "nationality_name": "Vietnam",
        "player_face_url": "https://cdn.sofifa.net/players/200/104/22_120.png" 
    }
]
#### Get Player v1/player/id
GET http://localhost:1705/v1/player/6426b9347fa27cfbe3d8ea5f
#### Get All Player

GET http://localhost:1705/v1/player

### DELETE PLAYER
DELETE http://localhost:1705/v1/player/6426b9347fa27cfbe3d8ea5f

### REGISTER
POST http://localhost:1705/auth/register
Content-Type: application/json

{
    "username": "dannguyen2",
    "password": "12345"
}



#### LOGIN

POST http://localhost:1705/auth/login
Content-Type: application/json

{
    "username": "dannguyen2",
    "password": "12345"
}


#### Add Player by Author
POST  http://localhost:1705/user/player
Content-Type: application/json
#Authorization: Bearer <token lay o accessToken khi login>
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI1ZDJiNWEyNDU2OWI5MGNjOWUyMGQiLCJpYXQiOjE2ODA4ODE1Mjd9.v-f8Ry793gb8ggGu4sFEjoUUeZ8GFPqo8YLxVm44CYM

{
    "long_name": "Ly Bach",
    "player_positions": "Gk",
    "value_eur": "7200",
    "age": 19,
    "dob": "2003-11-07",
    "club_name": "HungYen City",
    "nationality_name": "Vietnam",
    "player_face_url": "https://cdn.sofifa.net/players/200/145/22_122.png"

}


### GET PLAYER by Author
GET http://localhost:1705/user/player
#Authorization: Bearer <token lay o accessToken khi login>
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI1ZDJiNWEyNDU2OWI5MGNjOWUyMGQiLCJpYXQiOjE2ODA1NDEzNDR9.zODweVtpMXTQDXNoZNJvhGU-Hyxm0v6Wd7_LZ-C-iCY


#### UPDATE PLAYER by Author
PUT http://localhost:1705/user/player/642b1e36ad3ad8fd515b57e6
Content-Type: application/json
#Authorization: Bearer <token lay o accessToken khi login>
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI1ZDJiNWEyNDU2OWI5MGNjOWUyMGQiLCJpYXQiOjE2ODA1NDEzNDR9.zODweVtpMXTQDXNoZNJvhGU-Hyxm0v6Wd7_LZ-C-iCY

{
    "long_name": "Nguyen Di Dan",
    "value_eur": "17000",
    "age": 21,
    "dob": "2002-05-17",
    "club_name": "HungYen City",
    "nationality_name": "Vietnam"
}

### DELETE PLAYER by Author
DELETE http://localhost:1705/user/player/642b1e36ad3ad8fd515b57e6
#Authorization: Bearer <token lay o accessToken khi login>
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI1ZDJiNWEyNDU2OWI5MGNjOWUyMGQiLCJpYXQiOjE2ODA1NDEzNDR9.zODweVtpMXTQDXNoZNJvhGU-Hyxm0v6Wd7_LZ-C-iCY