## ADD MANY
POST http://localhost:8000/v1/player/many
Content-Type: application/json

[
    {
        "long_name": "Nguyen Di Dan",
        "player_position": ["RW", "CAM"],
        "value_eur": "17000",
        "age": 21,
        "dob": "2002-05-17",
        "club_name": "HungYen City",
        "nationality_name": "Vietnam",
        "player_face_url": "https://cdn.sofifa.net/players/200/145/22_120.png" 
    },
    {
        "long_name": "Nguyen Van Thang",
        "player_position": ["LW", "ST"],
        "value_eur": "24800",
        "age": 19,
        "dob": "2004-04-28",
        "club_name": "AnThi District",
        "nationality_name": "Vietnam",
        "player_face_url": "https://cdn.sofifa.net/players/200/104/22_120.png" 
    }
]
#### Get Player v1/player/id
GET http://localhost:1705/v1/player/6426b9347fa27cfbe3d8ea5f
#### Get All Player

GET http://localhost:1705/v1/player

### DELETE PLAYER
DELETE http://localhost:1705/v1/player/6426b9347fa27cfbe3d8ea5f





### REGISTER
POST http://localhost:1705/auth/register
Content-Type: application/json

{
    "username": "dannguyen2",
    "password": "12345"
}



#### LOGIN

POST http://localhost:1705/auth/login
Content-Type: application/json

{
    "username": "ThangElnino2004@",
    "password": "admin"
}


#### Add Player by Author
POST  http://localhost:1705/user/player/many
Content-Type: application/json
#Authorization: Bearer <token lay o accessToken khi login>
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM1MzA3N2E3MDEwNWVlODI3ZTg4ZWEiLCJpYXQiOjE2ODEyMDc0MzF9.BSjUqNmWxUoe0ZQ0VpF8DeY8CwXYVqUyDOE2M-Agz-8

[
{"long_name":"Raul Albiol Tortajada","player_positions":"CB","value_eur":8000000.0,"age":35,"dob":"1985-09-04","club_name":"Villarreal CF","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/157/481/22_120.png"}
,{"long_name":"Lukasz Fabianski","player_positions":"GK","value_eur":3400000.0,"age":36,"dob":"1985-04-18","club_name":"West Ham United","nationality_name":"Poland","player_face_url":"https://cdn.sofifa.net/players/164/835/22_120.png"}
,{"long_name":"Salvatore Sirigu","player_positions":"GK","value_eur":5000000.0,"age":34,"dob":"1987-01-12","club_name":"Genoa","nationality_name":"Italy","player_face_url":"https://cdn.sofifa.net/players/168/435/22_120.png"}
,{"long_name":"Ivan Rakitic","player_positions":"CM","value_eur":18500000.0,"age":33,"dob":"1988-03-10","club_name":"Sevilla FC","nationality_name":"Croatia","player_face_url":"https://cdn.sofifa.net/players/168/651/22_120.png"}
,{"long_name":"Gareth Frank Bale","player_positions":"RM, RW","value_eur":25000000.0,"age":31,"dob":"1989-07-16","club_name":"Real Madrid CF","nationality_name":"Wales","player_face_url":"https://cdn.sofifa.net/players/173/731/22_120.png"}
,{"long_name":"Rui Pedro dos Santos Patricio","player_positions":"GK","value_eur":10000000.0,"age":33,"dob":"1988-02-15","club_name":"Roma","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/178/005/22_120.png"}
,{"long_name":"Ever Maximiliano David Banega","player_positions":"CDM, CM","value_eur":15000000.0,"age":33,"dob":"1988-06-29","club_name":"Al Shabab","nationality_name":"Argentina","player_face_url":"https://cdn.sofifa.net/players/178/562/22_120.png"}
,{"long_name":"Miralem Pjanic","player_positions":"CM","value_eur":25000000.0,"age":31,"dob":"1990-04-02","club_name":"Be\u015fikta\u015f JK","nationality_name":"Bosnia and Herzegovina","player_face_url":"https://cdn.sofifa.net/players/180/206/22_120.png"}
,{"long_name":"Yuri Berchiche Izeta","player_positions":"LB","value_eur":22000000.0,"age":31,"dob":"1990-02-10","club_name":"Athletic Club de Bilbao","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/183/512/22_120.png"}
,{"long_name":"Lars Edi Stindl","player_positions":"CAM, ST","value_eur":24000000.0,"age":32,"dob":"1988-08-26","club_name":"Borussia Monchengladbach","nationality_name":"Germany","player_face_url":"https://cdn.sofifa.net/players/187/072/22_120.png"}
,{"long_name":"Oscar dos Santos Emboaba Junior","player_positions":"CAM, CM, LW","value_eur":30000000.0,"age":29,"dob":"1991-09-09","club_name":"Shanghai Port FC","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/188/152/22_120.png"}
,{"long_name":"Kevin Trapp","player_positions":"GK","value_eur":20500000.0,"age":30,"dob":"1990-07-08","club_name":"Eintracht Frankfurt","nationality_name":"Germany","player_face_url":"https://cdn.sofifa.net/players/188/943/22_120.png"}
,{"long_name":"Philippe Coutinho Correia","player_positions":"CAM, LW, CM","value_eur":30000000.0,"age":29,"dob":"1992-06-12","club_name":"FC Barcelona","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/189/242/22_120.png"}
,{"long_name":"Christian Dannemann Eriksen","player_positions":"CM, CAM","value_eur":29500000.0,"age":29,"dob":"1992-02-14","club_name":"Inter","nationality_name":"Denmark","player_face_url":"https://cdn.sofifa.net/players/190/460/22_120.png"}
,{"long_name":"Daley Blind","player_positions":"CB, CDM, LB","value_eur":21000000.0,"age":31,"dob":"1990-03-09","club_name":"Ajax","nationality_name":"Netherlands","player_face_url":"https://cdn.sofifa.net/players/190/815/22_120.png"}
,{"long_name":"Mario Gotze","player_positions":"CAM, CM","value_eur":30000000.0,"age":29,"dob":"1992-06-03","club_name":"PSV","nationality_name":"Germany","player_face_url":"https://cdn.sofifa.net/players/192/318/22_120.png"}
,{"long_name":"Alphonse Areola","player_positions":"GK","value_eur":26000000.0,"age":28,"dob":"1993-02-27","club_name":"West Ham United","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/193/105/22_120.png"}
,{"long_name":"Jesus Manuel Corona Ruiz","player_positions":"RM, RB, RW","value_eur":30500000.0,"age":28,"dob":"1993-01-06","club_name":"FC Porto","nationality_name":"Mexico","player_face_url":"https://cdn.sofifa.net/players/193/165/22_120.png"}
,{"long_name":"Alexandre Lacazette","player_positions":"ST","value_eur":30000000.0,"age":30,"dob":"1991-05-28","club_name":"Arsenal","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/193/301/22_120.png"}
,{"long_name":"Idrissa Gana Gueye","player_positions":"CDM, CM","value_eur":21500000.0,"age":31,"dob":"1989-09-26","club_name":"Paris Saint-Germain","nationality_name":"Senegal","player_face_url":"https://cdn.sofifa.net/players/193/474/22_120.png"}
,{"long_name":"Mario Figueira Fernandes","player_positions":"RB","value_eur":26500000.0,"age":30,"dob":"1990-09-19","club_name":"PFC CSKA Moscow","nationality_name":"Russia","player_face_url":"https://cdn.sofifa.net/players/193/525/22_120.png"}
,{"long_name":"Oliver Baumann","player_positions":"GK","value_eur":16000000.0,"age":31,"dob":"1990-06-02","club_name":"TSG Hoffenheim","nationality_name":"Germany","player_face_url":"https://cdn.sofifa.net/players/193/698/22_120.png"}
,{"long_name":"Norberto Murara Neto","player_positions":"GK","value_eur":16000000.0,"age":31,"dob":"1989-07-19","club_name":"FC Barcelona","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/194/404/22_120.png"}
,{"long_name":"Francisco Roman Alarcon Suarez","player_positions":"CAM, CM, LW","value_eur":30000000.0,"age":29,"dob":"1992-04-21","club_name":"Real Madrid CF","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/197/781/22_120.png"}
,{"long_name":"Wilfried Zaha","player_positions":"CF, LM, ST","value_eur":31000000.0,"age":28,"dob":"1992-11-10","club_name":"Crystal Palace","nationality_name":"C\u00f4te d'Ivoire","player_face_url":"https://cdn.sofifa.net/players/198/717/22_120.png"}
,{"long_name":"Luis Fernando Muriel Fruto","player_positions":"ST","value_eur":30000000.0,"age":30,"dob":"1991-04-16","club_name":"Atalanta","nationality_name":"Colombia","player_face_url":"https://cdn.sofifa.net/players/199/110/22_120.png"}
,{"long_name":"Anthony Lopes","player_positions":"GK","value_eur":23000000.0,"age":30,"dob":"1990-10-01","club_name":"Olympique Lyonnais","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/199/482/22_120.png"}
,{"long_name":"Jose Angel Gomez Campana","player_positions":"CM, LM, RM","value_eur":30500000.0,"age":28,"dob":"1993-05-31","club_name":"Levante Union Deportiva","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/199/823/22_120.png"}
,{"long_name":"Gabriel Armando de Abreu","player_positions":"CB","value_eur":25000000.0,"age":30,"dob":"1990-11-26","club_name":"Valencia CF","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/201/305/22_120.png"}
,{"long_name":"Jordan Veretout","player_positions":"CDM, CM","value_eur":29500000.0,"age":28,"dob":"1993-03-01","club_name":"Roma","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/201/519/22_120.png"}
,{"long_name":"Jesus Joaquin Fernandez Saez de la Torre","player_positions":"RW","value_eur":32500000.0,"age":27,"dob":"1993-11-19","club_name":"Sevilla FC","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/202/651/22_120.png"}
,{"long_name":"Thorgan Hazard","player_positions":"LM, CF","value_eur":30500000.0,"age":28,"dob":"1993-03-29","club_name":"Borussia Dortmund","nationality_name":"Belgium","player_face_url":"https://cdn.sofifa.net/players/203/486/22_120.png"}
,{"long_name":"Juan Bernat Velasco","player_positions":"LB","value_eur":27500000.0,"age":28,"dob":"1993-03-01","club_name":"Paris Saint-Germain","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/205/069/22_120.png"}
,{"long_name":"Cristian Portugues Manzanera","player_positions":"RW, RM, LW","value_eur":30000000.0,"age":29,"dob":"1992-05-21","club_name":"Real Sociedad","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/205/070/22_120.png"}
,{"long_name":"Hakan Kalhanoglu","player_positions":"CAM, LM","value_eur":35000000.0,"age":27,"dob":"1994-02-08","club_name":"Inter","nationality_name":"Turkey","player_face_url":"https://cdn.sofifa.net/players/208/128/22_120.png"}
,{"long_name":"Emre Can","player_positions":"CM, CB, CDM","value_eur":35000000.0,"age":27,"dob":"1994-01-12","club_name":"Borussia Dortmund","nationality_name":"Germany","player_face_url":"https://cdn.sofifa.net/players/208/333/22_120.png"}
,{"long_name":"Saul Niguez Esclapez","player_positions":"CM, LM","value_eur":39500000.0,"age":26,"dob":"1994-11-21","club_name":"Chelsea","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/208/421/22_120.png"}
,{"long_name":"Marten Elco de Roon","player_positions":"CDM, CM","value_eur":25500000.0,"age":30,"dob":"1991-03-29","club_name":"Atalanta","nationality_name":"Netherlands","player_face_url":"https://cdn.sofifa.net/players/208/461/22_120.png"}
,{"long_name":"Yassine Bounou","player_positions":"GK","value_eur":20500000.0,"age":30,"dob":"1991-04-05","club_name":"Sevilla FC","nationality_name":"Morocco","player_face_url":"https://cdn.sofifa.net/players/209/981/22_120.png"}
,{"long_name":"Alejandro Grimaldo Garcia","player_positions":"LB, LM, LWB","value_eur":37000000.0,"age":25,"dob":"1995-09-20","club_name":"SL Benfica","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/210/035/22_120.png"}
,{"long_name":"Alessio Romagnoli","player_positions":"CB","value_eur":31500000.0,"age":26,"dob":"1995-01-12","club_name":"AC Milan","nationality_name":"Italy","player_face_url":"https://cdn.sofifa.net/players/210/413/22_120.png"}
,{"long_name":"Domenico Berardi","player_positions":"RW, RM","value_eur":33500000.0,"age":26,"dob":"1994-08-01","club_name":"U.S. Sassuolo Calcio","nationality_name":"Italy","player_face_url":"https://cdn.sofifa.net/players/210/935/22_120.png"}
,{"long_name":"Nicolas Alejandro Tagliafico","player_positions":"LB","value_eur":27500000.0,"age":28,"dob":"1992-08-31","club_name":"Ajax","nationality_name":"Argentina","player_face_url":"https://cdn.sofifa.net/players/211/256/22_120.png"}
,{"long_name":"Pierluigi Gollini","player_positions":"GK","value_eur":35000000.0,"age":26,"dob":"1995-03-18","club_name":"Tottenham Hotspur","nationality_name":"Italy","player_face_url":"https://cdn.sofifa.net/players/211/515/22_120.png"}
,{"long_name":"Niklas Sule","player_positions":"CB, RB","value_eur":40500000.0,"age":25,"dob":"1995-09-03","club_name":"FC Bayern Munchen","nationality_name":"Germany","player_face_url":"https://cdn.sofifa.net/players/212/190/22_120.png"}
,{"long_name":"Alex Nicolao Telles","player_positions":"LB","value_eur":27500000.0,"age":28,"dob":"1992-12-15","club_name":"Manchester United","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/212/462/22_120.png"}
,{"long_name":"Anderson Souza Conceicao","player_positions":"CF, ST, CAM","value_eur":35500000.0,"age":27,"dob":"1994-02-01","club_name":"Al Nassr","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/212/523/22_120.png"}
,{"long_name":"Rodrigo Javier De Paul","player_positions":"CM, CF","value_eur":35000000.0,"age":27,"dob":"1994-05-24","club_name":"Atletico de Madrid","nationality_name":"Argentina","player_face_url":"https://cdn.sofifa.net/players/212/616/22_120.png"}
,{"long_name":"Rafael Alexandre Fernandes Ferreira da Silva","player_positions":"RM, LM","value_eur":30500000.0,"age":28,"dob":"1993-05-17","club_name":"SL Benfica","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/216/547/22_120.png"}
,{"long_name":"Diego Carlos Santos Silva","player_positions":"CB","value_eur":30500000.0,"age":28,"dob":"1993-03-15","club_name":"Sevilla FC","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/219/693/22_120.png"}
,{"long_name":"Ante Rebic","player_positions":"LM, ST","value_eur":32500000.0,"age":27,"dob":"1993-09-21","club_name":"AC Milan","nationality_name":"Croatia","player_face_url":"https://cdn.sofifa.net/players/220/018/22_120.png"}
,{"long_name":"Clement Nicolas Laurent Lenglet","player_positions":"CB","value_eur":37500000.0,"age":26,"dob":"1995-06-17","club_name":"FC Barcelona","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/220/440/22_120.png"}
,{"long_name":"James Maddison","player_positions":"CAM, CM","value_eur":41500000.0,"age":24,"dob":"1996-11-23","club_name":"Leicester City","nationality_name":"England","player_face_url":"https://cdn.sofifa.net/players/220/697/22_120.png"}
,{"long_name":"Manuel Locatelli","player_positions":"CDM, CM","value_eur":42000000.0,"age":23,"dob":"1998-01-08","club_name":"Juventus","nationality_name":"Italy","player_face_url":"https://cdn.sofifa.net/players/222/077/22_120.png"}
,{"long_name":"Martin Odegaard","player_positions":"CAM, CM","value_eur":49000000.0,"age":22,"dob":"1998-12-17","club_name":"Arsenal","nationality_name":"Norway","player_face_url":"https://cdn.sofifa.net/players/222/665/22_120.png"}
,{"long_name":"Ruben Diogo da Silva Neves","player_positions":"CM","value_eur":46000000.0,"age":24,"dob":"1997-03-13","club_name":"Wolverhampton Wanderers","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/224/293/22_120.png"}
,{"long_name":"Diogo Jose Teixeira da Silva","player_positions":"LW, ST","value_eur":46000000.0,"age":24,"dob":"1996-12-04","club_name":"Liverpool","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/224/458/22_120.png"}
,{"long_name":"Joe Gomez","player_positions":"CB","value_eur":43500000.0,"age":24,"dob":"1997-05-23","club_name":"Liverpool","nationality_name":"England","player_face_url":"https://cdn.sofifa.net/players/225/100/22_120.png"}
,{"long_name":"Fabian Ruiz Pena","player_positions":"CM","value_eur":42000000.0,"age":25,"dob":"1996-04-03","club_name":"Napoli","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/226/271/22_120.png"}
,{"long_name":"Christian Mate Pulisic","player_positions":"LW, RW, LM","value_eur":49000000.0,"age":22,"dob":"1998-09-18","club_name":"Chelsea","nationality_name":"United States","player_face_url":"https://cdn.sofifa.net/players/227/796/22_120.png"}
,{"long_name":"Joao Maria Lobo Alves Palhinha Goncalves","player_positions":"CDM, CM","value_eur":41000000.0,"age":25,"dob":"1995-07-09","club_name":"Sporting CP","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/229/391/22_120.png"}
,{"long_name":"Dayotchanculle Oswald Upamecano","player_positions":"CB","value_eur":64000000.0,"age":22,"dob":"1998-10-27","club_name":"FC Bayern Munchen","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/229/558/22_120.png"}
,{"long_name":"Mario Hermoso Canseco","player_positions":"CB, LB","value_eur":35500000.0,"age":26,"dob":"1995-06-18","club_name":"Atletico de Madrid","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/229/668/22_120.png"}
,{"long_name":"Leon Bailey Butler","player_positions":"RM, RW, LW","value_eur":41500000.0,"age":23,"dob":"1997-08-09","club_name":"Aston Villa","nationality_name":"Jamaica","player_face_url":"https://cdn.sofifa.net/players/229/906/22_120.png"}
,{"long_name":"Ben Chilwell","player_positions":"LWB, LB","value_eur":40500000.0,"age":24,"dob":"1996-12-21","club_name":"Chelsea","nationality_name":"England","player_face_url":"https://cdn.sofifa.net/players/229/984/22_120.png"}
,{"long_name":"Raphael William Anjos Rochedo","player_positions":"GK","value_eur":10000000.0,"age":33,"dob":"1988-02-29","club_name":"RB Bragantino","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/230/168/22_120.png"}
,{"long_name":"Josue Durval Chiamulera Vaz","player_positions":"CB","value_eur":25500000.0,"age":29,"dob":"1992-02-29","club_name":"Gremio","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/230/375/22_120.png"}
,{"long_name":"Unai Simon Mendibil","player_positions":"GK","value_eur":34500000.0,"age":24,"dob":"1997-06-11","club_name":"Athletic Club de Bilbao","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/230/869/22_120.png"}
,{"long_name":"Richarlison de Andrade","player_positions":"ST, LW, LM","value_eur":46500000.0,"age":24,"dob":"1997-05-10","club_name":"Everton","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/231/943/22_120.png"}
,{"long_name":"Cristian Gabriel Romero","player_positions":"CB","value_eur":41500000.0,"age":23,"dob":"1998-04-27","club_name":"Tottenham Hotspur","nationality_name":"Argentina","player_face_url":"https://cdn.sofifa.net/players/232/488/22_120.png"}
,{"long_name":"Denzel Justus Morris Dumfries","player_positions":"RB","value_eur":35000000.0,"age":25,"dob":"1996-04-18","club_name":"Inter","nationality_name":"Netherlands","player_face_url":"https://cdn.sofifa.net/players/233/096/22_120.png"}
,{"long_name":"Raphael Dias Belloli","player_positions":"RM, RW","value_eur":46000000.0,"age":24,"dob":"1996-12-14","club_name":"Leeds United","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/233/419/22_120.png"}
,{"long_name":"Alexander Isak","player_positions":"ST","value_eur":45000000.0,"age":21,"dob":"1999-09-21","club_name":"Real Sociedad","nationality_name":"Sweden","player_face_url":"https://cdn.sofifa.net/players/233/731/22_120.png"}
,{"long_name":"Declan Rice","player_positions":"CDM, CM","value_eur":43000000.0,"age":22,"dob":"1999-01-14","club_name":"West Ham United","nationality_name":"England","player_face_url":"https://cdn.sofifa.net/players/234/378/22_120.png"}
,{"long_name":"Alphonso Boyle Davies","player_positions":"LB, LM","value_eur":57000000.0,"age":20,"dob":"2000-11-02","club_name":"FC Bayern Munchen","nationality_name":"Canada","player_face_url":"https://cdn.sofifa.net/players/234/396/22_120.png"}
,{"long_name":"Florian Christian Neuhaus","player_positions":"CM","value_eur":46000000.0,"age":24,"dob":"1997-03-16","club_name":"Borussia Monchengladbach","nationality_name":"Germany","player_face_url":"https://cdn.sofifa.net/players/234/943/22_120.png"}
,{"long_name":"Youssef En-Nesyri","player_positions":"ST, LW","value_eur":44000000.0,"age":24,"dob":"1997-06-01","club_name":"Sevilla FC","nationality_name":"Morocco","player_face_url":"https://cdn.sofifa.net/players/235/410/22_120.png"}
,{"long_name":"Tanguy Ndombele Alvaro","player_positions":"CAM, CM, CDM","value_eur":46000000.0,"age":24,"dob":"1996-12-28","club_name":"Tottenham Hotspur","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/235/569/22_120.png"}
,{"long_name":"Tomas Soucek","player_positions":"CDM, CM","value_eur":36000000.0,"age":26,"dob":"1995-02-27","club_name":"West Ham United","nationality_name":"Czech Republic","player_face_url":"https://cdn.sofifa.net/players/236/792/22_120.png"}
,{"long_name":"Eder Gabriel Militao","player_positions":"CB","value_eur":56500000.0,"age":23,"dob":"1998-01-18","club_name":"Real Madrid CF","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/240/130/22_120.png"}
,{"long_name":"Ferran Torres Garcia","player_positions":"RW, ST","value_eur":68500000.0,"age":21,"dob":"2000-02-29","club_name":"Manchester City","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/241/461/22_120.png"}
,{"long_name":"Pau Francisco Torres","player_positions":"CB","value_eur":56500000.0,"age":24,"dob":"1997-01-16","club_name":"Villarreal CF","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/241/464/22_120.png"}
,{"long_name":"Dominik Livakovic","player_positions":"GK","value_eur":35000000.0,"age":26,"dob":"1995-01-09","club_name":"Dinamo Zagreb","nationality_name":"Croatia","player_face_url":"https://cdn.sofifa.net/players/241/671/22_120.png"}
,{"long_name":"Daniel Olmo Carvajal","player_positions":"CAM, CF","value_eur":46000000.0,"age":23,"dob":"1998-05-07","club_name":"RB Leipzig","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/244/260/22_120.png"}
,{"long_name":"Joaquin Sanchez Rodriguez","player_positions":"RM, LM","value_eur":8500000.0,"age":39,"dob":"1981-07-21","club_name":"Real Betis Balompie","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/045/186/22_120.png"}
,{"long_name":"Burak Yolmaz","player_positions":"ST","value_eur":11000000.0,"age":35,"dob":"1985-07-15","club_name":"LOSC Lille","nationality_name":"Turkey","player_face_url":"https://cdn.sofifa.net/players/124/375/22_120.png"}
,{"long_name":"Luis Carlos Almeida da Cunha","player_positions":"LW, LM","value_eur":12000000.0,"age":34,"dob":"1986-11-17","club_name":"Orlando City Soccer Club","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/139/068/22_120.png"}
,{"long_name":"Andre-Pierre Christian Gignac","player_positions":"ST, CF","value_eur":11000000.0,"age":35,"dob":"1985-12-05","club_name":"Tigres U.A.N.L.","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/153/244/22_120.png"}
,{"long_name":"Hector Miguel Herrera Lopez","player_positions":"CM","value_eur":21000000.0,"age":31,"dob":"1990-04-19","club_name":"Atletico de Madrid","nationality_name":"Mexico","player_face_url":"https://cdn.sofifa.net/players/156/519/22_120.png"}
,{"long_name":"Andrea Consigli","player_positions":"GK","value_eur":4400000.0,"age":34,"dob":"1987-01-27","club_name":"U.S. Sassuolo Calcio","nationality_name":"Italy","player_face_url":"https://cdn.sofifa.net/players/163/489/22_120.png"}
,{"long_name":"Steve Mandanda","player_positions":"GK","value_eur":2900000.0,"age":36,"dob":"1985-03-28","club_name":"Olympique de Marseille","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/163/705/22_120.png"}
,{"long_name":"Gonzalo Gerardo Higuain","player_positions":"ST","value_eur":16500000.0,"age":33,"dob":"1987-12-10","club_name":"Inter Miami CF","nationality_name":"Argentina","player_face_url":"https://cdn.sofifa.net/players/167/664/22_120.png"}
,{"long_name":"Jose Miguel da Rocha Fonte","player_positions":"CB","value_eur":4600000.0,"age":37,"dob":"1983-12-22","club_name":"LOSC Lille","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/171/791/22_120.png"}
,{"long_name":"Jan Vertonghen","player_positions":"CB","value_eur":8500000.0,"age":34,"dob":"1987-04-24","club_name":"SL Benfica","nationality_name":"Belgium","player_face_url":"https://cdn.sofifa.net/players/172/871/22_120.png"}
,{"long_name":"Lucas Pezzini Leiva","player_positions":"CDM","value_eur":9000000.0,"age":34,"dob":"1987-01-09","club_name":"Lazio","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/176/266/22_120.png"}
,{"long_name":"Antonio Adan Garrido","player_positions":"GK","value_eur":4400000.0,"age":34,"dob":"1987-05-13","club_name":"Sporting CP","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/178/086/22_120.png"}
,{"long_name":"Ivan Perisic","player_positions":"LM, LW, LWB","value_eur":20500000.0,"age":32,"dob":"1989-02-02","club_name":"Inter","nationality_name":"Croatia","player_face_url":"https://cdn.sofifa.net/players/181/458/22_120.png"}
,{"long_name":"Arturo Erasmo Vidal Pardo","player_positions":"CM","value_eur":12000000.0,"age":34,"dob":"1987-05-22","club_name":"Inter","nationality_name":"Chile","player_face_url":"https://cdn.sofifa.net/players/181/872/22_120.png"}
,{"long_name":"Max Bennet Kruse","player_positions":"CF, CAM","value_eur":16500000.0,"age":33,"dob":"1988-03-19","club_name":"1. FC Union Berlin","nationality_name":"Germany","player_face_url":"https://cdn.sofifa.net/players/183/574/22_120.png"}
,{"long_name":"Marko Arnautovic","player_positions":"ST","value_eur":21000000.0,"age":32,"dob":"1989-04-19","club_name":"Bologna","nationality_name":"Austria","player_face_url":"https://cdn.sofifa.net/players/184/200/22_120.png"}
,{"long_name":"Marlos Romero Bonfim","player_positions":"CAM, RM","value_eur":16000000.0,"age":33,"dob":"1988-06-07","club_name":"Shakhtar Donetsk","nationality_name":"Ukraine","player_face_url":"https://cdn.sofifa.net/players/187/754/22_120.png"}
,{"long_name":"Benjamin Andre","player_positions":"CDM, CM","value_eur":21500000.0,"age":30,"dob":"1990-08-03","club_name":"LOSC Lille","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/190/674/22_120.png"}
,{"long_name":"Nicolas Hernan Gonzalo Otamendi","player_positions":"CB","value_eur":12500000.0,"age":33,"dob":"1988-02-12","club_name":"SL Benfica","nationality_name":"Argentina","player_face_url":"https://cdn.sofifa.net/players/192/366/22_120.png"}
,{"long_name":"Thomas Joseph Delaney","player_positions":"CDM, CM","value_eur":22000000.0,"age":29,"dob":"1991-09-03","club_name":"Sevilla FC","nationality_name":"Denmark","player_face_url":"https://cdn.sofifa.net/players/193/283/22_120.png"}
,{"long_name":"Aitor Fernandez Abarisketa","player_positions":"GK","value_eur":17000000.0,"age":30,"dob":"1991-05-03","club_name":"Levante Union Deportiva","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/193/314/22_120.png"}
,{"long_name":"Andy Delort","player_positions":"ST","value_eur":25500000.0,"age":29,"dob":"1991-10-09","club_name":"OGC Nice","nationality_name":"Algeria","player_face_url":"https://cdn.sofifa.net/players/193/983/22_120.png"}
,{"long_name":"Kevin Kampl","player_positions":"CM, CDM","value_eur":24500000.0,"age":30,"dob":"1990-10-09","club_name":"RB Leipzig","nationality_name":"Slovenia","player_face_url":"https://cdn.sofifa.net/players/195/365/22_120.png"}
,{"long_name":"Daniel William John Ings","player_positions":"ST","value_eur":26500000.0,"age":28,"dob":"1992-07-23","club_name":"Aston Villa","nationality_name":"England","player_face_url":"https://cdn.sofifa.net/players/195/859/22_120.png"}
,{"long_name":"Luis Miguel Afonso Fernandes","player_positions":"CM, RM","value_eur":21000000.0,"age":31,"dob":"1989-10-06","club_name":"SL Benfica","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/197/965/22_120.png"}
,{"long_name":"Jonathan Viera Ramos","player_positions":"CAM","value_eur":21500000.0,"age":31,"dob":"1989-10-01","club_name":"Union Deportiva Las Palmas","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/198/164/22_120.png"}
,{"long_name":"James David Rodriguez Rubio","player_positions":"RW, CAM, CM","value_eur":25500000.0,"age":29,"dob":"1991-07-12","club_name":"Everton","nationality_name":"Colombia","player_face_url":"https://cdn.sofifa.net/players/198/710/22_120.png"}
,{"long_name":"Danilo Luiz da Silva","player_positions":"RB, LB, CB","value_eur":22500000.0,"age":29,"dob":"1991-07-15","club_name":"Juventus","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/199/304/22_120.png"}
,{"long_name":"Sergio Roberto Carnicer","player_positions":"RB, CM, RM","value_eur":22500000.0,"age":29,"dob":"1992-02-07","club_name":"FC Barcelona","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/199/564/22_120.png"}
,{"long_name":"Jasper Cillessen","player_positions":"GK","value_eur":13000000.0,"age":32,"dob":"1989-04-22","club_name":"Valencia CF","nationality_name":"Netherlands","player_face_url":"https://cdn.sofifa.net/players/199/987/22_120.png"}
,{"long_name":"Steven Berghuis","player_positions":"RW","value_eur":25500000.0,"age":29,"dob":"1991-12-19","club_name":"Ajax","nationality_name":"Netherlands","player_face_url":"https://cdn.sofifa.net/players/200/260/22_120.png"}
,{"long_name":"Francisco Alcacer Garcia","player_positions":"ST","value_eur":28000000.0,"age":27,"dob":"1993-08-30","club_name":"Villarreal CF","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/200/454/22_120.png"}
,{"long_name":"Jose Ignacio Fernandez Iglesias","player_positions":"CB, RB, LB","value_eur":17500000.0,"age":31,"dob":"1990-01-18","club_name":"Real Madrid CF","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/200/724/22_120.png"}
,{"long_name":"Danilo Luis Helio Pereira","player_positions":"CDM, CM","value_eur":22000000.0,"age":29,"dob":"1991-09-09","club_name":"Paris Saint-Germain","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/200/888/22_120.png"}
,{"long_name":"Lucas Rodrigues Moura da Silva","player_positions":"RM, CF","value_eur":26000000.0,"age":28,"dob":"1992-08-13","club_name":"Tottenham Hotspur","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/200/949/22_120.png"}
,{"long_name":"Agustin Federico Marchesin","player_positions":"GK","value_eur":8500000.0,"age":33,"dob":"1988-03-16","club_name":"FC Porto","nationality_name":"Argentina","player_face_url":"https://cdn.sofifa.net/players/201/095/22_120.png"}
,{"long_name":"James Tarkowski","player_positions":"CB","value_eur":24500000.0,"age":28,"dob":"1992-11-19","club_name":"Burnley","nationality_name":"England","player_face_url":"https://cdn.sofifa.net/players/202/695/22_120.png"}
,{"long_name":"Alessandro Florenzi","player_positions":"RB, RWB","value_eur":22000000.0,"age":30,"dob":"1991-03-11","club_name":"AC Milan","nationality_name":"Italy","player_face_url":"https://cdn.sofifa.net/players/203/551/22_120.png"}
,{"long_name":"Tomas Vaclik","player_positions":"GK","value_eur":13000000.0,"age":32,"dob":"1989-03-29","club_name":"Olympiacos CFP","nationality_name":"Czech Republic","player_face_url":"https://cdn.sofifa.net/players/204/120/22_120.png"}
,{"long_name":"Kurt Happy Zouma","player_positions":"CB","value_eur":30000000.0,"age":26,"dob":"1994-10-27","club_name":"West Ham United","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/204/311/22_120.png"}
,{"long_name":"Donigo Martinez Berridi","player_positions":"CB","value_eur":21000000.0,"age":30,"dob":"1991-05-17","club_name":"Athletic Club de Bilbao","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/204/525/22_120.png"}
,{"long_name":"Vilmos Tamas Orban","player_positions":"CB","value_eur":24500000.0,"age":28,"dob":"1992-11-03","club_name":"RB Leipzig","nationality_name":"Hungary","player_face_url":"https://cdn.sofifa.net/players/204/638/22_120.png"}
,{"long_name":"Arkadiusz Krystian Milik","player_positions":"ST","value_eur":30000000.0,"age":27,"dob":"1994-02-28","club_name":"Olympique de Marseille","nationality_name":"Poland","player_face_url":"https://cdn.sofifa.net/players/205/175/22_120.png"}
,{"long_name":"James Ward-Prowse","player_positions":"CM","value_eur":33500000.0,"age":26,"dob":"1994-11-01","club_name":"Southampton","nationality_name":"England","player_face_url":"https://cdn.sofifa.net/players/205/569/22_120.png"}
,{"long_name":"Alessio Cragno","player_positions":"GK","value_eur":23500000.0,"age":27,"dob":"1994-06-28","club_name":"Cagliari","nationality_name":"Italy","player_face_url":"https://cdn.sofifa.net/players/205/659/22_120.png"}
,{"long_name":"Edin Visca","player_positions":"RM, RW","value_eur":21500000.0,"age":31,"dob":"1990-02-17","club_name":"\u0130stanbul Ba\u015fak\u015fehir FK","nationality_name":"Bosnia and Herzegovina","player_face_url":"https://cdn.sofifa.net/players/205/678/22_120.png"}
,{"long_name":"Maximilian Arnold","player_positions":"CDM, CM","value_eur":26500000.0,"age":27,"dob":"1994-05-27","club_name":"VfL Wolfsburg","nationality_name":"Germany","player_face_url":"https://cdn.sofifa.net/players/206/511/22_120.png"}
,{"long_name":"Leandro Daniel Paredes","player_positions":"CDM, CM","value_eur":28000000.0,"age":27,"dob":"1994-06-29","club_name":"Paris Saint-Germain","nationality_name":"Argentina","player_face_url":"https://cdn.sofifa.net/players/207/439/22_120.png"}
,{"long_name":"Adnan Januzaj","player_positions":"RW, RM","value_eur":28000000.0,"age":26,"dob":"1995-02-05","club_name":"Real Sociedad","nationality_name":"Belgium","player_face_url":"https://cdn.sofifa.net/players/208/330/22_120.png"}
,{"long_name":"Emil Peter Forsberg","player_positions":"CAM, CF","value_eur":25500000.0,"age":29,"dob":"1991-10-23","club_name":"RB Leipzig","nationality_name":"Sweden","player_face_url":"https://cdn.sofifa.net/players/208/448/22_120.png"}
,{"long_name":"Andrea Belotti","player_positions":"ST","value_eur":30000000.0,"age":27,"dob":"1993-12-20","club_name":"Torino F.C.","nationality_name":"Italy","player_face_url":"https://cdn.sofifa.net/players/208/596/22_120.png"}
,{"long_name":"Lucas Vazquez Iglesias","player_positions":"RW, RB, RM","value_eur":25000000.0,"age":30,"dob":"1991-07-01","club_name":"Real Madrid CF","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/208/618/22_120.png"}
,{"long_name":"Frederico Rodrigues de Paula Santos","player_positions":"CDM, CM","value_eur":22500000.0,"age":28,"dob":"1993-03-05","club_name":"Manchester United","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/209/297/22_120.png"}
,{"long_name":"Adrien Rabiot","player_positions":"CM, CDM","value_eur":30000000.0,"age":26,"dob":"1995-04-03","club_name":"Juventus","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/210/008/22_120.png"}
,{"long_name":"Rui Tiago Dantas da Silva","player_positions":"GK","value_eur":25500000.0,"age":27,"dob":"1994-02-07","club_name":"Real Betis Balompie","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/210/385/22_120.png"}
,{"long_name":"Piotr Sebastian Zielinski","player_positions":"CM, CAM","value_eur":29500000.0,"age":27,"dob":"1994-05-20","club_name":"Napoli","nationality_name":"Poland","player_face_url":"https://cdn.sofifa.net/players/210/406/22_120.png"}
,{"long_name":"Otavio Edmilson da Silva Monteiro","player_positions":"LM, RM, CM","value_eur":30500000.0,"age":26,"dob":"1995-02-09","club_name":"FC Porto","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/210/411/22_120.png"}
,{"long_name":"Darwin Daniel Machis Marcano","player_positions":"LM, RM, ST","value_eur":26000000.0,"age":28,"dob":"1993-02-07","club_name":"Granada CF","nationality_name":"Venezuela","player_face_url":"https://cdn.sofifa.net/players/210/463/22_120.png"}
,{"long_name":"Anthony Martial","player_positions":"ST, LM","value_eur":34500000.0,"age":25,"dob":"1995-12-05","club_name":"Manchester United","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/211/300/22_120.png"}
,{"long_name":"Odisseas Vlachodimos","player_positions":"GK","value_eur":23500000.0,"age":27,"dob":"1994-04-26","club_name":"SL Benfica","nationality_name":"Greece","player_face_url":"https://cdn.sofifa.net/players/211/990/22_120.png"}
,{"long_name":"Julian Brandt","player_positions":"CAM, CM, CF","value_eur":36000000.0,"age":25,"dob":"1996-05-02","club_name":"Borussia Dortmund","nationality_name":"Germany","player_face_url":"https://cdn.sofifa.net/players/212/194/22_120.png"}
,{"long_name":"Juan Agustin Musso","player_positions":"GK","value_eur":23500000.0,"age":27,"dob":"1994-05-06","club_name":"Atalanta","nationality_name":"Argentina","player_face_url":"https://cdn.sofifa.net/players/214/979/22_120.png"}
,{"long_name":"Carlos Joaquin Correa","player_positions":"CF, ST, CAM","value_eur":31000000.0,"age":26,"dob":"1994-08-13","club_name":"Inter","nationality_name":"Argentina","player_face_url":"https://cdn.sofifa.net/players/215/330/22_120.png"}
,{"long_name":"Inaki Williams Arthuer","player_positions":"ST, RW","value_eur":30000000.0,"age":27,"dob":"1994-06-15","club_name":"Athletic Club de Bilbao","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/216/201/22_120.png"}
,{"long_name":"Matteo Politano","player_positions":"RM, RW","value_eur":27500000.0,"age":27,"dob":"1993-08-03","club_name":"Napoli","nationality_name":"Italy","player_face_url":"https://cdn.sofifa.net/players/216/409/22_120.png"}
,{"long_name":"Jose Luis Morales Nogales","player_positions":"ST, LM","value_eur":16500000.0,"age":33,"dob":"1987-07-23","club_name":"Levante Union Deportiva","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/216/475/22_120.png"}
,{"long_name":"Djene Dakonam Ortega","player_positions":"CB","value_eur":24000000.0,"age":29,"dob":"1991-12-31","club_name":"Getafe CF","nationality_name":"Togo","player_face_url":"https://cdn.sofifa.net/players/217/940/22_120.png"}
,{"long_name":"Hans Hateboer","player_positions":"RWB, RB, RM","value_eur":25000000.0,"age":27,"dob":"1994-01-09","club_name":"Atalanta","nationality_name":"Netherlands","player_face_url":"https://cdn.sofifa.net/players/220/093/22_120.png"}
,{"long_name":"Martin Dubravka","player_positions":"GK","value_eur":13000000.0,"age":32,"dob":"1989-01-15","club_name":"Newcastle United","nationality_name":"Slovakia","player_face_url":"https://cdn.sofifa.net/players/220/407/22_120.png"}
,{"long_name":"Donny van de Beek","player_positions":"CM, CAM, CDM","value_eur":38500000.0,"age":24,"dob":"1997-04-18","club_name":"Manchester United","nationality_name":"Netherlands","player_face_url":"https://cdn.sofifa.net/players/221/363/22_120.png"}
,{"long_name":"Dominic Calvert-Lewin","player_positions":"ST","value_eur":37500000.0,"age":24,"dob":"1997-03-16","club_name":"Everton","nationality_name":"England","player_face_url":"https://cdn.sofifa.net/players/221/479/22_120.png"}
,{"long_name":"Hirving Rodrigo Lozano Bahena","player_positions":"RW, LW","value_eur":31000000.0,"age":25,"dob":"1995-07-30","club_name":"Napoli","nationality_name":"Mexico","player_face_url":"https://cdn.sofifa.net/players/221/992/22_120.png"}
,{"long_name":"David Soria Solis","player_positions":"GK","value_eur":20500000.0,"age":28,"dob":"1993-04-04","club_name":"Getafe CF","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/223/952/22_120.png"}
,{"long_name":"Kalvin Phillips","player_positions":"CDM, CM, CB","value_eur":32500000.0,"age":25,"dob":"1995-12-02","club_name":"Leeds United","nationality_name":"England","player_face_url":"https://cdn.sofifa.net/players/224/081/22_120.png"}
,{"long_name":"Goncalo Manuel Ganchinho Guedes","player_positions":"LM, ST, CF","value_eur":39000000.0,"age":24,"dob":"1996-11-29","club_name":"Valencia CF","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/224/411/22_120.png"}
,{"long_name":"Konrad Laimer","player_positions":"CDM, CM, RB","value_eur":33500000.0,"age":24,"dob":"1997-05-27","club_name":"RB Leipzig","nationality_name":"Austria","player_face_url":"https://cdn.sofifa.net/players/225/375/22_120.png"}
,{"long_name":"Nicolas Pepe","player_positions":"RM, RW","value_eur":30500000.0,"age":26,"dob":"1995-05-29","club_name":"Arsenal","nationality_name":"C\u00f4te d'Ivoire","player_face_url":"https://cdn.sofifa.net/players/226/110/22_120.png"}
,{"long_name":"Nordi Mukiele Mulere","player_positions":"RWB, CB, RM","value_eur":34500000.0,"age":23,"dob":"1997-11-01","club_name":"RB Leipzig","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/226/166/22_120.png"}
,{"long_name":"Giovani Lo Celso","player_positions":"CM, CAM","value_eur":35500000.0,"age":25,"dob":"1996-04-09","club_name":"Tottenham Hotspur","nationality_name":"Argentina","player_face_url":"https://cdn.sofifa.net/players/226/226/22_120.png"}
,{"long_name":"Alejandro Remiro Gargallo","player_positions":"GK","value_eur":26000000.0,"age":26,"dob":"1995-03-24","club_name":"Real Sociedad","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/227/127/22_120.png"}
,{"long_name":"Yeray Alvarez Lopez","player_positions":"CB","value_eur":28000000.0,"age":26,"dob":"1995-01-24","club_name":"Athletic Club de Bilbao","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/227/950/22_120.png"}
,{"long_name":"Lorenzo Pellegrini","player_positions":"CAM, CM, CDM","value_eur":38000000.0,"age":25,"dob":"1996-06-19","club_name":"Roma","nationality_name":"Italy","player_face_url":"https://cdn.sofifa.net/players/228/251/22_120.png"}
,{"long_name":"Juan Everton Mestres de Mesquita","player_positions":"CB, CDM","value_eur":25000000.0,"age":25,"dob":"1996-02-29","club_name":"Clube Atletico Mineiro","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/230/225/22_120.png"}
,{"long_name":"Adryan Juliano Zonta Torres","player_positions":"LWB, LB","value_eur":22500000.0,"age":29,"dob":"1992-02-29","club_name":"RB Bragantino","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/230/256/22_120.png"}
,{"long_name":"Rosberto J. Dourado Santos","player_positions":"CDM, CM, CAM","value_eur":27000000.0,"age":21,"dob":"2000-02-29","club_name":"Sport Club Corinthians Paulista","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/230/258/22_120.png"}
,{"long_name":"Lourival Adnan Beretta Barbosa","player_positions":"ST, CF","value_eur":25500000.0,"age":29,"dob":"1992-02-29","club_name":"RB Bragantino","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/230/294/22_120.png"}
,{"long_name":"Welington Kaue Dano Nascimento","player_positions":"LB, LM","value_eur":27500000.0,"age":21,"dob":"2000-02-29","club_name":"Clube Atletico Mineiro","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/230/347/22_120.png"}
,{"long_name":"Marvin Oswaldo Rangel Azevedo","player_positions":"ST","value_eur":25500000.0,"age":29,"dob":"1992-02-29","club_name":"Flamengo","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/230/430/22_120.png"}
,{"long_name":"Ruslan Malinovskyi","player_positions":"CF, CM","value_eur":26500000.0,"age":28,"dob":"1993-05-04","club_name":"Atalanta","nationality_name":"Ukraine","player_face_url":"https://cdn.sofifa.net/players/231/969/22_120.png"}
,{"long_name":"Christopher Nkunku","player_positions":"CAM, CM, CF","value_eur":39000000.0,"age":23,"dob":"1997-11-14","club_name":"RB Leipzig","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/232/411/22_120.png"}
,{"long_name":"Lucas Tolentino Coelho de Lima","player_positions":"CM, CAM","value_eur":38500000.0,"age":23,"dob":"1997-08-27","club_name":"Olympique Lyonnais","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/233/927/22_120.png"}
,{"long_name":"Carlos Soler Barragan","player_positions":"CM, RM, LM","value_eur":51500000.0,"age":24,"dob":"1997-01-02","club_name":"Valencia CF","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/234/153/22_120.png"}
,{"long_name":"Harvey Lewis Barnes","player_positions":"LM, LW","value_eur":35000000.0,"age":23,"dob":"1997-12-09","club_name":"Leicester City","nationality_name":"England","player_face_url":"https://cdn.sofifa.net/players/234/742/22_120.png"}
,{"long_name":"Houssem Aouar","player_positions":"CM, CAM","value_eur":38500000.0,"age":23,"dob":"1998-06-30","club_name":"Olympique Lyonnais","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/234/906/22_120.png"}
,{"long_name":"Manuel Lazzari","player_positions":"RWB","value_eur":25000000.0,"age":27,"dob":"1993-11-29","club_name":"Lazio","nationality_name":"Italy","player_face_url":"https://cdn.sofifa.net/players/235/374/22_120.png"}
,{"long_name":"Reece James","player_positions":"RWB, RB","value_eur":37000000.0,"age":21,"dob":"1999-12-08","club_name":"Chelsea","nationality_name":"England","player_face_url":"https://cdn.sofifa.net/players/238/074/22_120.png"}
,{"long_name":"Marc Cucurella Saseta","player_positions":"LM, LB","value_eur":41500000.0,"age":22,"dob":"1998-07-22","club_name":"Brighton & Hove Albion","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/239/231/22_120.png"}
,{"long_name":"Pedro Antonio Pereira Goncalves","player_positions":"RW, CM","value_eur":51500000.0,"age":23,"dob":"1998-06-28","club_name":"Sporting CP","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/240/950/22_120.png"}
,{"long_name":"Moussa Diaby","player_positions":"LW, RW","value_eur":52500000.0,"age":21,"dob":"1999-07-07","club_name":"Bayer 04 Leverkusen","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/241/852/22_120.png"}
,{"long_name":"Sergio Reguilon Rodriguez","player_positions":"LB","value_eur":32500000.0,"age":24,"dob":"1996-12-16","club_name":"Tottenham Hotspur","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/245/279/22_120.png"}
,{"long_name":"Edmond Faycal Tapsoba","player_positions":"CB","value_eur":48500000.0,"age":22,"dob":"1999-02-02","club_name":"Bayer 04 Leverkusen","nationality_name":"Burkina Faso","player_face_url":"https://cdn.sofifa.net/players/247/263/22_120.png"}
,{"long_name":"Dejan Kulusevski","player_positions":"RW, CF","value_eur":58000000.0,"age":21,"dob":"2000-04-25","club_name":"Juventus","nationality_name":"Sweden","player_face_url":"https://cdn.sofifa.net/players/247/394/22_120.png"}
,{"long_name":"Renan Augusto Lodi dos Santos","player_positions":"LB","value_eur":36500000.0,"age":23,"dob":"1998-04-08","club_name":"Atletico de Madrid","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/251/573/22_120.png"}
,{"long_name":"Pedro Gonzalez Lopez","player_positions":"CM","value_eur":54000000.0,"age":18,"dob":"2002-11-25","club_name":"FC Barcelona","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/251/854/22_120.png"}
,{"long_name":"Gianluigi Buffon","player_positions":"GK","value_eur":2300000.0,"age":43,"dob":"1978-01-28","club_name":"Parma","nationality_name":"Italy","player_face_url":"https://cdn.sofifa.net/players/001/179/22_120.png"}
,{"long_name":"Francisco Guillermo Ochoa Magana","player_positions":"GK","value_eur":2300000.0,"age":35,"dob":"1985-07-13","club_name":"Club America","nationality_name":"Mexico","player_face_url":"https://cdn.sofifa.net/players/140/233/22_120.png"}
,{"long_name":"Igor Akinfeev","player_positions":"GK","value_eur":2300000.0,"age":35,"dob":"1986-04-08","club_name":"PFC CSKA Moscow","nationality_name":"Russia","player_face_url":"https://cdn.sofifa.net/players/148/119/22_120.png"}
,{"long_name":"Joao Filipe Iria Santos Moutinho","player_positions":"CM","value_eur":9500000.0,"age":34,"dob":"1986-09-08","club_name":"Wolverhampton Wanderers","nationality_name":"Portugal","player_face_url":"https://cdn.sofifa.net/players/162/347/22_120.png"}
,{"long_name":"Jonathan Grant Evans","player_positions":"CB","value_eur":10000000.0,"age":33,"dob":"1988-01-03","club_name":"Leicester City","nationality_name":"Northern Ireland","player_face_url":"https://cdn.sofifa.net/players/169/588/22_120.png"}
,{"long_name":"Raul Garcia Escudero","player_positions":"ST, CAM","value_eur":10500000.0,"age":34,"dob":"1986-07-11","club_name":"Athletic Club de Bilbao","nationality_name":"Spain","player_face_url":"https://cdn.sofifa.net/players/171/579/22_120.png"}
,{"long_name":"Marek Hamsik","player_positions":"CM, CDM, CAM","value_eur":13000000.0,"age":33,"dob":"1987-07-27","club_name":"Trabzonspor","nationality_name":"Slovakia","player_face_url":"https://cdn.sofifa.net/players/171/877/22_120.png"}
,{"long_name":"Daniel Wass","player_positions":"RB, RM, CM","value_eur":14500000.0,"age":32,"dob":"1989-05-31","club_name":"Valencia CF","nationality_name":"Denmark","player_face_url":"https://cdn.sofifa.net/players/172/522/22_120.png"}
,{"long_name":"Simon Luc Hildebert Mignolet","player_positions":"GK","value_eur":7000000.0,"age":33,"dob":"1988-03-06","club_name":"Club Brugge KV","nationality_name":"Belgium","player_face_url":"https://cdn.sofifa.net/players/173/426/22_120.png"}
,{"long_name":"Marcelo Vieira da Silva Junior","player_positions":"LB","value_eur":11000000.0,"age":33,"dob":"1988-05-12","club_name":"Real Madrid CF","nationality_name":"Brazil","player_face_url":"https://cdn.sofifa.net/players/176/676/22_120.png"}
,{"long_name":"Dimitri Payet","player_positions":"LW, CAM","value_eur":10000000.0,"age":34,"dob":"1987-03-29","club_name":"Olympique de Marseille","nationality_name":"France","player_face_url":"https://cdn.sofifa.net/players/177/388/22_120.png"}
,{"long_name":"Medhi Amine El Mouttaqi Benatia","player_positions":"CB","value_eur":7000000.0,"age":34,"dob":"1987-04-17","club_name":"Fatih Karagumruk S.K.","nationality_name":"Morocco","player_face_url":"https://cdn.sofifa.net/players/177/509/22_120.png"}
]


### GET PLAYER by Author
GET http://localhost:1705/user/player
#Authorization: Bearer <token lay o accessToken khi login>
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI1ZDJiNWEyNDU2OWI5MGNjOWUyMGQiLCJpYXQiOjE2ODA1NDEzNDR9.zODweVtpMXTQDXNoZNJvhGU-Hyxm0v6Wd7_LZ-C-iCY


#### UPDATE PLAYER by Author
PUT http://localhost:1705/user/player/642b1e36ad3ad8fd515b57e6
Content-Type: application/json
#Authorization: Bearer <token lay o accessToken khi login>
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI1ZDJiNWEyNDU2OWI5MGNjOWUyMGQiLCJpYXQiOjE2ODA1NDEzNDR9.zODweVtpMXTQDXNoZNJvhGU-Hyxm0v6Wd7_LZ-C-iCY

{
    "long_name": "Nguyen Di Dan",
    "value_eur": "17000",
    "age": 21,
    "dob": "2002-05-17",
    "club_name": "HungYen City",
    "nationality_name": "Vietnam"
}

### DELETE PLAYER by Author
DELETE http://localhost:1705/user/player/642b1e36ad3ad8fd515b57e6
#Authorization: Bearer <token lay o accessToken khi login>
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI1ZDJiNWEyNDU2OWI5MGNjOWUyMGQiLCJpYXQiOjE2ODA1NDEzNDR9.zODweVtpMXTQDXNoZNJvhGU-Hyxm0v6Wd7_LZ-C-iCY